### ISSUE TITLE
Error when using with pandas 2.0.0

### ISSUE THREAD

**Issue by shreyas-arvindekar** [salilab/PMI_analysis#10]
The current version of pmi_analysis (version number bcbf4b7) does not work with the latest version of pandas (2.0.0). It returns the following error:
```
Traceback (most recent call last):
  File "/home/shreyas/wdr/analysis/run_analysis_trajectories_w_skip2.py", line 59, in <module>
    AT.get_psi_stats()
  File "/home/shreyas/imp-clean/pmi_analysis/pyext/src/analysis_trajectories.py", line 1691, in get_psi_stats
    DF_stat_nuis = DF_stat_nuis.append(
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/shreyas/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'.
```
